### ISSUE TITLE
Still showing deleted, archived and spam sites

### ISSUE THREAD

**Issue by Zodiac1978** [alordiel/dropdown-multisite-selector#3]
Although a fix is reported in the support forums:
https://wordpress.org/support/topic/exclude-non-active-sites/

it seems to be not implemented:
https://github.com/alordiel/dropdown-multisite-selector/blob/master/functions/functions.php#L37-L67

**Comment by alordiel** [comment]
Thanks for reporting this (and the other bug #4 ). I hope I can make the changes available to the WordPress repo.
