### ISSUE TITLE
works in wp5.4.1. with DIVI but DIVI sites won't work on mobile (iPhone)

### ISSUE THREAD

**Issue by lisandi** [alordiel/dropdown-multisite-selector#8]
Hi Thanks for fixing.
The menu now works in WordPress 5.4.1 with DIVI when inserted to any menu area i.e. Top Menu

But it is not working on all DIVI pages on iPhone - all non Divi Pages work fine.
The menu appears and you can scroll to the page and you can select the subsite you like to display next but the menu doesn't opens up the page - it does simply nothing!

[https://t3pack.com/fashion/](https://t3pack.com/fashion/)
This is a subsite which uses DIVI
https://t3pack.com/4/ a subsite without DIVI - simple twentytwenty - here it is working fine on mobile.

**Comment by alordiel** [comment]
I'm closing this since it seems that the site is not active. Please let me know if you need help with this and if the error is still presented.
