### ISSUE TITLE
Drop down lists only 101 nodes instead of all 172

### ISSUE THREAD

**Issue by lisandi** [alordiel/dropdown-multisite-selector#9]
We have currently 172 public sites but only 101 sites get listed with the drop down.
https://t3pack.com/bakery/
Is there any limitation in place and how can we remove that as all sites should get listed.

I am not sure why it is limited to 101 as usually the <option> is unlimited depending on browser and OS Ram 
http://jsfiddle.net/Mare6/
as you can test here it is running fine with 1000 or 5000 entries so why it does not display more than 101?

**Comment by Zodiac1978** [comment]
The limitation to 100 was fixed with version 0.5 (after `wp_get_sites` was replaced with `get_sites`).

Are you still using `wp_get_sites` in a filter perhaps? Still on 0.5 or below?

Sorry for asking such a basic question ...

**Comment by lisandi** [comment]
I use * Version:           0.7
 * Author:            alordiel

$sites_arguments = array(
'public'  => 1,
'archive' => 0,
'deleted' => 0,
'spam'    => 0,
'orderby' => array( 'path' ),
                'number'=>500,
);

You have to insert that value
or even better make it variable and let the user insert the value.
https://developer.wordpress.org/reference/functions/get_sites/

*'number'*
*(int)* Maximum number of sites to retrieve. Default 100.

**Comment by Zodiac1978** [comment]
Oh yes, it is also limited to 100.

Could then be added with the new filter `dms_sites_arguments`.

**Comment by lisandi** [comment]
It would be good to have a filter option here on that screen without
entering the code, when choosing all sites of a WMS
[image: Screen Shot 2020-06-22 at 20.46.33.png]

**Comment by alordiel** [comment]
Hi,
I have merged your pull request which set the limit to 1000. 
Also there is `apply_filter` which you can use to change the default parameters I have set. Here it is `dms_sites_arguments`. 
I guess I should add some sort of documentation for the filters that can be used.

**Comment by lisandi** [comment]
Thanks Alexander - yes documentation would be great

With kind regards,
*
<https://about.me/andibecker?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=edit_panel&utm_content=thumb>
Andreas Becker about.me/andibecker
<https://about.me/andibecker?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=edit_panel&utm_content=thumb>
**LisAndi Co. Ltd.*, Phuket, Thailand (lisandi.com)
15/21 M.2 Viset Road, Rawai, Muang, Phuket, Thailand 83130

Phone: +66 (0)76 530 595
GTalk/Facetime/eMail:  andi@lisandi.com
Mobile/WhatsApp/Line: +66 (0)81 606 3378
Facebook/Line/Messenger: andibecker
Skype: lisandi
--------------------------------------------------
